### PR TITLE
Switch to nightly_coverage to fix stable coverage runs

### LINKED ISSUE #18: Switch to `coverage_nightly` ?
I was trying to run coverage tests something that depends on this crate and noticed that it fails with:

```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> C:\Users\Eugene\.cargo\registry\src\github.com-1ecc6299db9ec823\encase-0.4.0\src\lib.rs:2:23
  |
2 | #![cfg_attr(coverage, feature(no_coverage))]
  |   
```

According to https://github.com/taiki-e/cargo-llvm-cov#exclude-function-from-coverage this could be solved by a command line flag or a change to checking for `coverage_nightly` instead of `coverage`. Would a PR be acceptable to switch to coverage_nightly or is it preferable to use the command line flag for llvm-cov?

### PR DESCRIPTION
**Pull request by emarcotte**
Closes #18 

I also tried to make some of the tests pass when no feature flags are passed on `cargo test` with stable, but wasn't sure what to do about wrapper.rs which fails with:

```
test tests/pass/wrappers.rs [should pass] ... error
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> tests/pass/wrappers.rs:1:1
  |
1 | #![feature(trivial_bounds)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
``` 

Probably could address the mint usage in a more targeted fashion and completely killing the file. Happy to tweak this (or revert it entirely).

The basic test plan I've been using is `cargo llvm-cov` both on this repo and in a bevy project I have patched to point to my PR.

### CODE REVIEW

**Review by teoxoy — CHANGES_REQUESTED** [review]
Thanks for the PR!

I run the tests in CI using nightly due to the `trivial_bounds` feature needed for that test.
So, I think we can undo the `#![cfg(feature = "mint")]` additions for now and this should be good to go.

**Comment by emarcotte** [comment]
> Thanks for the PR!
> 
> I run the tests in CI using nightly due to the `trivial_bounds` feature needed for that test. So, I think we can undo the `#![cfg(feature = "mint")]` additions for now and this should be good to go.

Reverted the mint check in tests/. Let me know if anything else I should check/change.

File: src/utils.rs [hunk 1]
```diff
@@ -1,5 +1,5 @@
 #[track_caller]
-#[cfg_attr(coverage, no_coverage)]
+#[cfg_attr(coverage_nightly, feature(no_coverage))]
```
Comment (teoxoy) [inline src/utils.rs:2]:
```suggestion
#[cfg_attr(coverage_nightly, no_coverage)]
```

**Review by teoxoy — CHANGES_REQUESTED** [review]

**Review by teoxoy — APPROVED** [review]

**Comment by teoxoy** [comment]
@emarcotte Thanks! I released v0.4.1
